name: CI/CD Pipeline Bai 3

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Kéo mã nguồn về (Checkout code)
        uses: actions/checkout@v4

      - name: Cài đặt môi trường Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Chạy vòng đời Maven (Test & Package)

        working-directory: ./Bai03
        run: mvn -B clean test package

      - name: Lưu trữ tệp .jar (Upload Artifact)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: mathutils-app-jar

          path: Bai03/target/*.jar