name: CI/CD Bai 03

on:
  push:
    branches: [ "main" ]
    # CHỈ CHẠY khi có file trong thư mục bai03 thay đổi
    paths:
      - 'bai03/**'
      - '.github/workflows/ci-bai03.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    # BẮT BUỘC MAVEN PHẢI CHẠY BÊN TRONG THƯ MỤC bai03
    defaults:
      run:
        working-directory: ./bai03

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Build and Test
        run: mvn -B clean test package

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: mathutils-app-jar
          # Đường dẫn tính từ thư mục gốc
          path: bai03/target/*.jar